import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import List from '../components/List'

export default function Home() {

  return (
    <>
      <Head>
        <title>MoonMakers Movies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div className={styles.banner} >
          <h1>El mejor contenido al alcanse de tu mano</h1>
        </div>

        <List
          key={1}
          name="New Movies"
          url="https://api.themoviedb.org/3/movie/now_playing?api_key="
          />

        <List
          key={2}
          name="Popular Movies"
          url="https://api.themoviedb.org/3/movie/popular?api_key="
        />

        <br />
        <br />
        <br />
        <br />
      </main>
    </>
  )
}
